spring.application.name=M5-API-GATEWAY
server.port=9999

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.prefer-ip-address=true

# Actuator
management.endpoints.web.exposure.include=health,info,metrics,gateway

# ----------------------------- api gateway routes -----------------------------

# Greet Service
spring.cloud.gateway.server.webflux.routes[0].id=greet-service-route
spring.cloud.gateway.server.webflux.routes[0].uri=lb://M3-GREET-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/greet/**

# Welcome Service
spring.cloud.gateway.server.webflux.routes[1].id=welcome-service-route
spring.cloud.gateway.server.webflux.routes[1].uri=lb://M4-WELCOME-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/welcome/**