spring.application.name=M3-GREET-SERVICE
#server.port=8081
# commented port number for checking working of the load balancing

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# Spring Boot Admin
spring.boot.admin.client.url=http://localhost:9090

# Actuator
management.endpoints.web.exposure.include=health,info,metrics

# Tracing / Zipkin
management.tracing.sampling.probability=1.0
management.tracing.export.zipkin.endpoint=http://localhost:9411/api/v2/spans