spring.datasource.url=jdbc:mysql://localhost:3306/student_database
spring.datasource.username=root
spring.datasource.password=root
# telling jpa to create table
# upsert method: first will check select query then perform insert operation
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true